### ISSUE TITLE
prepareDnsChallenge cleanup exception

### ISSUE THREAD

**Issue by itomaldonado** [tazjin/kubernetes-letsencrypt#63]
May be related (or not) to #61 but I am getting this error when it tries clean up the DNS challenge. I built the docker container myself (using your `gradlew` commands)so I am not sure if it something I did.

```
{"@timestamp":"2017-07-06T23:17:48.347+00:00","@version":1,"message":"Record _acme-challenge.some.example.com updated in ns-xxx.awsdns.com.","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"Thread-5","level":"INFO","level_value":20000}
Exception in thread "Thread-5" java.lang.ClassCastException: in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler$prepareDnsChallenge$cleanup$1 cannot be cast to java.lang.Runnable
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.prepareDnsChallenge(CertificateRequestHandler.kt:180)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.authorizeDomain(CertificateRequestHandler.kt:77)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.access$authorizeDomain(CertificateRequestHandler.kt:27)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler$requestCertificate$1.accept(CertificateRequestHandler.kt:41)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler$requestCertificate$1.accept(CertificateRequestHandler.kt:27)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.requestCertificate(CertificateRequestHandler.kt:41)
	at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager.handleCertificateRequest(ServiceManager.kt:64)
	at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager.access$handleCertificateRequest(ServiceManager.kt:20)
	at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager$reconcileService$1.run(ServiceManager.kt:45)
	at java.lang.Thread.run(Thread.java:745)
{"@timestamp":"2017-07-06T23:17:48.357+00:00","@version":1,"message":"Record _acme-challenge.some.example.com updated in ns-xxx.awsdns.com.","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"ForkJoinPool.commonPool-worker-0","level":"INFO","level_value":20000}
```

**Comment by itomaldonado** [comment]
More logs:


```
{"@timestamp":"2017-07-06T23:23:24.270+00:00","@version":1,"message":"http-outgoing-0 << \"<GetChangeResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><ChangeInfo><Id>/change/xxxxxxxx</Id><Status>INSYNC</Status><SubmittedAt>2017-07-06T23:22:44.769Z</SubmittedAt></ChangeInfo></GetChangeResponse>\"","logger_name":"org.apache.http.wire","thread_name":"Thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:24.271+00:00","@version":1,"message":"Connection [id: 0][route: {s}->https://route53.amazonaws.com:443] can be kept alive for 60.0 seconds","logger_name":"org.apache.http.impl.conn.PoolingHttpClientConnectionManager","thread_name":"Thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:24.271+00:00","@version":1,"message":"Connection released: [id: 0][route: {s}->https://route53.amazonaws.com:443][total kept alive: 1; route allocated: 1 of 50; total allocated: 1 of 50]","logger_name":"org.apache.http.impl.conn.PoolingHttpClientConnectionManager","thread_name":"Thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:24.271+00:00","@version":1,"message":"Received successful response: 200, AWS Request ID: xxxxxxxx","logger_name":"com.amazonaws.request","thread_name":"Thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:24.271+00:00","@version":1,"message":"x-amzn-RequestId: xxxxx","logger_name":"com.amazonaws.requestId","thread_name":"Thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:25.289+00:00","@version":1,"message":"Waiting for DNS record '_acme-challenge.some.example.com' update","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"Thread-1","level":"INFO","level_value":20000}
{"@timestamp":"2017-07-06T23:23:25.388+00:00","@version":1,"message":"Looking up _acme-challenge.xxx.some.example.com in ns-1.awsdns.com.","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"ForkJoinPool.commonPool-worker-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:25.388+00:00","@version":1,"message":"Looking up _acme-challenge.xxx.some.example.com in ns-2.awsdns.net.","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"Thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:25.395+00:00","@version":1,"message":"Record _acme-challenge.xxx.some.example.com updated in ns-2.awsdns.net.","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"Thread-1","level":"INFO","level_value":20000}
{"@timestamp":"2017-07-06T23:23:25.398+00:00","@version":1,"message":"Looking up _acme-challenge.xxx.some.example.com in ns-3.awsdns.org.","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"Thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:25.408+00:00","@version":1,"message":"Record _acme-challenge.xxx.some.example.com updated in ns-3.awsdns.org.","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"Thread-1","level":"INFO","level_value":20000}
{"@timestamp":"2017-07-06T23:23:25.412+00:00","@version":1,"message":"Looking up _acme-challenge.xxx.some.example.com in ns-4.awsdns.co.uk.","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"Thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:25.416+00:00","@version":1,"message":"Record _acme-challenge.xxx.some.example.com updated in ns-4.awsdns.co.uk.","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"Thread-1","level":"INFO","level_value":20000}
{"@timestamp":"2017-07-06T23:23:25.417+00:00","@version":1,"message":"Record _acme-challenge.xxx.some.example.com updated in ns-1.awsdns.com.","logger_name":"in.tazj.k8s.letsencrypt.util.DnsRecordObserver","thread_name":"ForkJoinPool.commonPool-worker-1","level":"INFO","level_value":20000}
Exception in thread "Thread-1" java.lang.ClassCastException: in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler$prepareDnsChallenge$cleanup$1 cannot be cast to java.lang.Runnable
    at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.prepareDnsChallenge(CertificateRequestHandler.kt:180)
    at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.authorizeDomain(CertificateRequestHandler.kt:77)
    at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.access$authorizeDomain(CertificateRequestHandler.kt:27)
    at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler$requestCertificate$1.accept(CertificateRequestHandler.kt:41)
    at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler$requestCertificate$1.accept(CertificateRequestHandler.kt:27)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
    at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
    at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.requestCertificate(CertificateRequestHandler.kt:41)
    at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager.handleCertificateRequest(ServiceManager.kt:64)
    at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager.access$handleCertificateRequest(ServiceManager.kt:20)
    at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager$reconcileService$1.run(ServiceManager.kt:45)
    at java.lang.Thread.run(Thread.java:745)
{"@timestamp":"2017-07-06T23:23:28.519+00:00","@version":1,"message":"Reconciliation request for xxx-service","logger_name":"in.tazj.k8s.letsencrypt.kubernetes.ServiceManager","thread_name":"pool-1-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:28.520+00:00","@version":1,"message":"Reconciliation request for kubernetes","logger_name":"in.tazj.k8s.letsencrypt.kubernetes.ServiceManager","thread_name":"pool-2-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:28.521+00:00","@version":1,"message":"Reconciliation request for kube-dns","logger_name":"in.tazj.k8s.letsencrypt.kubernetes.ServiceManager","thread_name":"pool-5-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:28.521+00:00","@version":1,"message":"Reconciliation request for kubernetes-dashboard","logger_name":"in.tazj.k8s.letsencrypt.kubernetes.ServiceManager","thread_name":"pool-5-thread-1","level":"DEBUG","level_value":10000}
{"@timestamp":"2017-07-06T23:23:28.533+00:00","@version":1,"message":"Service xxx-service requesting certificates: [xxx.some.example.com]","logger_name":"in.tazj.k8s.letsencrypt.kubernetes.ServiceManager","thread_name":"Thread-3","level":"INFO","level_value":20000}
{"@timestamp":"2017-07-06T23:23:28.534+00:00","@version":1,"message":"create","logger_name":"org.shredzone.acme4j.RegistrationBuilder","thread_name":"Thread-3","level":"DEBUG","level_value":10000}
```

**Comment by tazjin** [comment]
I wonder if this is something that broke in the Kotlin rewrite (`master` isn't entirely stable at the moment!). Will take a look, thanks!
