### ISSUE TITLE
Exception in thread "Thread-23"

### ISSUE THREAD

**Issue by chrisabrams** [tazjin/kubernetes-letsencrypt#78]
```
{"@timestamp":"2017-10-12T22:00:05.663+00:00","@version":1,"message":"Service gateway requesting certificates: [ditto.network, app.ditto.network]","logger_name":"in.tazj.k8s.letsencrypt.kubernetes.ServiceManager","thread_name":"Thread-27","level":"INFO","level_value":20000}
{"@timestamp":"2017-10-12T22:00:05.730+00:00","@version":1,"message":"Unexpected error while setting up registration: {}","logger_name":"in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler","thread_name":"Thread-27","level":"ERROR","level_value":40000,"stack_trace":"org.shredzone.acme4j.exception.AcmeNetworkException: Network error\n\tat org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:112)\n\tat org.shredzone.acme4j.provider.AbstractAcmeProvider.directory(AbstractAcmeProvider.java:55)\n\tat org.shredzone.acme4j.Session.readDirectory(Session.java:211)\n\tat org.shredzone.acme4j.Session.resourceUri(Session.java:186)\n\tat org.shredzone.acme4j.RegistrationBuilder.create(RegistrationBuilder.java:86)\n\tat in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.getRegistration(CertificateRequestHandler.kt:194)\n\tat in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.requestCertificate(CertificateRequestHandler.kt:37)\n\tat in.tazj.k8s.letsencrypt.kubernetes.ServiceManager.handleCertificateRequest(ServiceManager.kt:64)\n\tat in.tazj.k8s.letsencrypt.kubernetes.ServiceManager.access$handleCertificateRequest(ServiceManager.kt:20)\n\tat in.tazj.k8s.letsencrypt.kubernetes.ServiceManager$reconcileService$1.run(ServiceManager.kt:45)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty\n\tat sun.security.ssl.Alerts.getSSLException(Alerts.java:208)\n\tat sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)\n\tat sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)\n\tat sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)\n\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)\n\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)\n\tat sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)\n\tat sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)\n\tat sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)\n\tat org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:108)\n\t... 10 common frames omitted\nCaused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty\n\tat sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)\n\tat sun.security.validator.Validator.getInstance(Validator.java:179)\n\tat sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)\n\tat sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)\n\tat sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)\n\tat sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)\n\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)\n\tat sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)\n\tat sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)\n\tat sun.security.ssl.Handshaker.process_record(Handshaker.java:914)\n\tat sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)\n\tat sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)\n\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)\n\t... 15 common frames omitted\nCaused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty\n\tat java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)\n\tat java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)\n\tat java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)\n\tat sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)\n\t... 27 common frames omitted\n"}
Exception in thread "Thread-23" in.tazj.k8s.letsencrypt.util.LetsencryptException: Network error
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.getRegistration(CertificateRequestHandler.kt:202)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.requestCertificate(CertificateRequestHandler.kt:37)
	at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager.handleCertificateRequest(ServiceManager.kt:64)
	at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager.access$handleCertificateRequest(ServiceManager.kt:20)
	at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager$reconcileService$1.run(ServiceManager.kt:45)
	at java.lang.Thread.run(Thread.java:745)
```

Running on Google Cloud Platform. No clue what this error is :/

**Comment by tazjin** [comment]
Hmm, I haven't seen this one before. It seems to occur while either logging in to or creating a new LE "account" (i.e. a new key pair).

It could be a temporary issue on LE's side or something more significant. I'll take a look tomorrow!

**Comment by chrisabrams** [comment]
Looks like that was the case.
