### ISSUE TITLE
Failed due to invalid challenge

### ISSUE THREAD

**Issue by ensonic** [tazjin/kubernetes-letsencrypt#87]
Today I am getting this one one a test project repeatedly:
```
Exception in thread "Thread-4" in.tazj.k8s.letsencrypt.util.LetsencryptException: Failed due to invalid challenge
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.completeChallenge(CertificateRequestHandler.kt:153)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.authorizeDomain(CertificateRequestHandler.kt:78)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.access$authorizeDomain(CertificateRequestHandler.kt:27)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler$requestCertificate$1.accept(CertificateRequestHandler.kt:41)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler$requestCertificate$1.accept(CertificateRequestHandler.kt:27)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at in.tazj.k8s.letsencrypt.acme.CertificateRequestHandler.requestCertificate(CertificateRequestHandler.kt:41)
	at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager.handleCertificateRequest(ServiceManager.kt:64)
	at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager.access$handleCertificateRequest(ServiceManager.kt:20)
	at in.tazj.k8s.letsencrypt.kubernetes.ServiceManager$reconcileService$1.run(ServiceManager.kt:45)
	at java.lang.Thread.run(Thread.java:745)
```
The message is not super helpful to figure whats going on. Also can we please get a new release? Maybe this is already fixed?

**Comment by ensonic** [comment]
After a day this magically recovered and worked.

**Comment by ensonic** [comment]
Arrg. My DNS provider silently introduced CAA records. In the errors you throw from
./src/main/kotlin/in/tazj/k8s/letsencrypt/acme/CertificateRequestHandler.kt, it would be helpful to just fetch the challenge and dump it. The error has type and detail.

**Comment by tazjin** [comment]
Hey! I'm in vacation mode at the moment and not doing much software work :)

If you'd like to submit a change for fetching and logging the challenge I'd be happy to accept it, otherwise it will have to wait a little while - hopefully that's fine!

**Comment by ensonic** [comment]
I'll prep a change.
